spring:
  main:
    web-application-type: none
  application:
    name: Viniti Rubricator Parser

external-api:
  viniti:
    rubricator:
      url: http://scs.viniti.ru/rubtree/main.aspx?tree=RV
  cscsti:
    rubricator:
      url: http://scs.viniti.ru/rubtree/main.aspx?tree=RGNTI

db:
  neo4j:
    uri: bolt://localhost:7687
    username: neo4j
    password: venomvenom--
